### ISSUE TITLE
Pass id in onChange

### ISSUE THREAD

**Issue by AndrewCreer** [yogaboll/react-switch#2]
Not quite sure about pull requests etc....

I need to pass the id of the component back with new value, so I know which switch changed.

Cheers

<pre>
diff --git a/src/index.jsx b/src/index.jsx
index 9587351..b9c9fa6 100644
--- a/src/index.jsx
+++ b/src/index.jsx
@@ -38,12 +38,12 @@ class Switch extends Component {
 
   handleDragStop = (event) => {
     const { pos, isDragging } = this.state;
-    const { checked, onChange } = this.props;
+    const { checked, onChange, id } = this.props;
 
     // Simulate clicking the handle
     if (!isDragging) {
       this.setState({ startX: null, hasOutline: false });
-      onChange(!checked, event);
+      onChange(!checked, id, event);
       return;
     }
     if (checked) {
@@ -52,7 +52,7 @@ class Switch extends Component {
         return;
       }
       this.setState({ startX: null, isDragging: false, hasOutline: false });
-      onChange(false, event);
+      onChange(false, id, event);
       return;
     }
     if (pos < (this.checkedPos + this.uncheckedPos) / 2) {
@@ -60,7 +60,7 @@ class Switch extends Component {
       return;
     }
     this.setState({ startX: null, isDragging: false, hasOutline: false });
-    onChange(true, event);
+    onChange(true, id, event);
   }
 
   handleMouseDown = (event) => {
@@ -101,17 +101,17 @@ class Switch extends Component {
   }
 
   handleClick = (event) => {
-    const { checked, onChange } = this.props;
-    onChange(!checked, event);
+    const { checked, onChange, id } = this.props;
+    onChange(!checked, id, event);
   }
 
   handleKeyDown = (event) => {
-    const { checked, onChange } = this.props;
+    const { checked, onChange, id } = this.props;
     const { isDragging } = this.state;
     // Trigger change on spacebar and enter keys (in violation of wai-aria spec).
     if ((event.keyCode === 32 || event.keyCode === 13) && !isDragging) {
       event.preventDefault();
-      onChange(!checked, event);
+      onChange(!checked, id, event);
     }
   }
 
</pre>

**Comment by yogaboll** [comment]
Ok, I can see how this feature might be useful. Would you like to make a pull request to implement your changes?

If you do, I just want you to change the order of the arguments that are passed to onChange. `id` should be the third argument instead of second, so `onChange(!checked, id, event)` would become `onChange(!checked, event, id)`. This would avoid breaking existing code that uses the `event` argument.

If you're uncertain of how to make a pull request you can check out [this guide](https://github.com/Roshanjossey/first-contributions).

**Comment by yogaboll** [comment]
I implemented this change in the update (2.2.0) that was just published to npm. *id* is now the third argument in the onChange callback function.

I'm closing this issue.
